version: '3.1'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
        - "32181:32181"

  kafka:
    image: confluentinc/cp-kafka:3.2.0
    depends_on:
      - zookeeper
    #volumes:  # only maria does this in production
    #  - /data/scratch/kafka/ztf-logs:/logs
    #  - /data/scratch/kafka/ztf-data:/var/lib/kafka/data    
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
